---
- name: Docker container web app 
  block:
    - name: Wipe web app
      tags: wipe
      include_tasks: wipe_web_app.yml
    - name: Deploy web app
      tags: deploy
      include_tasks: push_docker_compose.yml