---
- name: Run Docker container
  community.docker.docker_container:
    name: "{{ docker_container }}"
    image: "{{ docker_image_name }}:{{ docker_image_version }}"
    state: started
    ports:
      - "{{internal_port}}:{{external_port}}"