version: "3"

networks:
  loki:

services:
  app_python:
    image: rakavaqaflow/app-python:latest
    container_name: app_python
    ports:
      - "5000:5000"
    logging: &logger
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - loki

  app_go:
    image: rakavaqaflow/app-go:latest
    container_name: app_go
    ports:
      - "9000:9000"
    networks:
      - loki
    logging:
       <<: *logger
    

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging:
       <<: *logger
    

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    logging:
       <<: *logger
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    entrypoint:
      - sh
      - -euc
      - /run.sh  
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - loki
    logging:
       <<: *logger
  
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/config.yml:/etc/prometheus/prometheus-config.yml"
    command:
      - "--config.file=/etc/prometheus/prometheus-config.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --tries=1 --spider http://localhost:9090/status || exit 1" ]
      timeout: 10s
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 750m
    logging: 
      <<: *logger
    networks:
      - loki